name: "tidyverse_joinfeaturecountsaccno"
description: Join genome accession numbers onto a collected featureCounts table
keywords:
  - featurecounts
  - join
  - genome
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - counts:
      type: file
      description: Collected featureCounts long-format table, as produced by COLLECT_FEATURECOUNTS
      pattern: "*.counts.tsv.gz"
  - g2ids:
      type: file
      description: File mapping genome accessions to ORF IDs
      pattern: "*genomes2orfs.tsv.gz"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - counts:
      type: file
      description: Counts TSV file with the genome accession column joined in
      pattern: "*.counts.tsv.gz"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
      ontologies:
        - edam: "http://edamontology.org/format_3750" # YAML
authors:
  - "@erikrikarddaniel"
