# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "gffread_proteins"
description: Translate the CDS features of a GFF into a protein FASTA named by CDS ID
keywords:
  - gff
  - cds
  - translation
  - protein
tools:
  - "gffread":
      description: "GFF/GTF utility providing format conversions, region filtering,
        FASTA sequence extraction and more."
      homepage: "https://ccb.jhu.edu/software/stringtie/gff.shtml#gffread"
      documentation: "https://ccb.jhu.edu/software/stringtie/gff.shtml#gffread"
      tool_dev_url: "https://github.com/gpertea/gffread"
      doi: "10.12688/f1000research.23297.2"
      licence: ["MIT"]
      identifier: biotools:gffread

input:
  - - meta:
        type: map
        description: Groovy Map containing genome information. e.g. `[
          id:'genome1' ]`
    - fna:
        type: file
        description: Genome nucleotide FASTA, optionally gzipped
        pattern: "*.{fna,fa,fasta}{,.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_1929"
    - gff:
        type: file
        description: Genome annotation in GFF3 format, optionally gzipped
        pattern: "*.{gff,gff3}{,.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_1975"
output:
  faa:
    - - meta:
          type: map
          description: Groovy Map containing genome information. e.g. `[
            id:'genome1' ]`
      - ${prefix}.faa.gz:
          type: file
          description: Gzipped protein FASTA, one record per CDS ID
          pattern: "*.faa.gz"
          ontologies:
            - edam: "http://edamontology.org/format_1929"
  versions_gffread:
    - - ${task.process}:
          type: string
          description: The name of the process
      - gffread:
          type: string
          description: The name of the tool
      - gffread --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - gffread:
          type: string
          description: The name of the tool
      - gffread --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@erikrikarddaniel"
maintainers:
  - "@erikrikarddaniel"
